module.exports = {
  info: jest.fn(),
  warning: jest.fn(),
  error: jest.fn(),
  debug: jest.fn(),
  setOutput: jest.fn(),
  setFailed: jest.fn(),
  getInput: jest.fn(),
  getBooleanInput: jest.fn(),
  getMultilineInput: jest.fn(),
  setSecret: jest.fn(),
  exportVariable: jest.fn(),
  addPath: jest.fn(),
  startGroup: jest.fn(),
  endGroup: jest.fn(),
  saveState: jest.fn(),
  getState: jest.fn(),
  group: jest.fn(),
  notice: jest.fn(),
  summary: {
    addRaw: jest.fn(),
    addCodeBlock: jest.fn(),
    addHeading: jest.fn(),
    addList: jest.fn(),
    addQuote: jest.fn(),
    addSeparator: jest.fn(),
    addTable: jest.fn(),
    clear: jest.fn(),
    emptyBuffer: jest.fn(),
    isEmptyBuffer: jest.fn(),
    stringify: jest.fn(),
    write: jest.fn(),
  }
}
